In [2]:
import tensorflow.compat.v1 as tf
import numpy as np

In [3]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


# Creating a graph

In [4]:
a = tf.constant([2,3,4,5])
b = tf.constant([6,7,8,9])

In [5]:
c = a + b

In [6]:
c

<tf.Tensor 'add:0' shape=(4,) dtype=int32>

In [7]:
type(c)

tensorflow.python.framework.ops.SymbolicTensor

In [8]:
with tf.Session() as sess:
    res_a , res_b , res_c = sess.run([a,b,c])

print(res_a)
print(res_b)
print(res_c)

[2 3 4 5]
[6 7 8 9]
[ 8 10 12 14]


I0000 00:00:1746430688.326866   23808 mlir_graph_optimization_pass.cc:425] MLIR V1 optimization pass is not enabled


# นำ random มา

In [9]:
ru1 = tf.random.uniform([10], dtype=tf.float64)
ru2 = tf.random.uniform([10, 50], dtype=tf.float32)
ru3 = tf.random.uniform([10, 50, 90], minval=0, maxval=100, dtype=tf.int32)

rad_ints1 = tf.random.normal([10], dtype=tf.float64)
rad_ints2 = tf.random.normal([10, 50], dtype=tf.float32)
rad_ints3 = tf.random.normal([10, 50, 90], dtype=tf.float64)

In [10]:
with tf.compat.v1.Session() as sess:
    res_a, res_b, res_c, res_d, res_e, res_f = sess.run([ru1, ru2, ru3, rad_ints1, rad_ints2, rad_ints3])

print("ru1 =", res_a)
print("ru2 = ", res_b)
print("ru3 = ", res_c)
print("rad_ints1 = ", res_d)
print("rad_ints2 = ", res_e)
print("rad_ints3 = ", res_f)

ru1 = [7.36651895e-01 9.03767437e-01 8.44667133e-01 4.59307805e-01
 3.92793169e-04 5.12421861e-02 9.19588296e-01 9.46644900e-01
 7.73858222e-01 2.81167951e-01]
ru2 =  [[0.04023063 0.41717398 0.5281733  0.13400292 0.7111372  0.2507112
  0.91086185 0.93639493 0.9552381  0.68259346 0.30265284 0.5194789
  0.31997848 0.98668945 0.3182552  0.06238341 0.0270052  0.6516694
  0.45483863 0.44912875 0.77971256 0.17444015 0.4257573  0.35424483
  0.45167196 0.90432465 0.79750407 0.3401084  0.54986703 0.5915532
  0.91916394 0.8878112  0.17907059 0.9036759  0.94877374 0.11933136
  0.16372359 0.1377449  0.44897664 0.9869149  0.7021259  0.9746975
  0.3737625  0.64647603 0.22739136 0.09991014 0.16184306 0.2522564
  0.14164329 0.19606888]
 [0.35986733 0.766745   0.6217035  0.38312387 0.29545295 0.69596756
  0.80472326 0.33207572 0.47027528 0.18001544 0.41849577 0.7344743
  0.99423933 0.89531887 0.0920732  0.15249336 0.5555464  0.04652107
  0.6765102  0.57774246 0.8396127  0.2763437  0.5175861  0.76568663

In [11]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow.compat.v1 as tf
import requests
tf.disable_v2_behavior()
sess = tf.Session()


In [12]:
housing_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
housing_header = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX',
  'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
cols_used = ['CRIM', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS',
'TAX', 'PTRATIO', 'B', 'LSTAT']
num_features = len(cols_used)


In [13]:
line = '0.00632  18.00  2.310   0.0  0.538'
parts = line.split(' ')
print(parts)


['0.00632', '', '18.00', '', '2.310', '', '', '0.0', '', '0.538']


In [14]:
housing_file = requests.get(housing_url)
lines = housing_file.text.strip().split('\n')  # ตัด \n ท้ายสุดออกด้วย
housing_data = []

for line in lines:
    if len(line) < 1:
        continue  # ข้ามบรรทัดว่าง
    parts = line.split(' ')
    clean_parts = [float(x) for x in parts if len(x) >= 1]
    housing_data.append(clean_parts)



In [15]:
[y for y in housing_file.text][0:15]

[' ', '0', '.', '0', '0', '6', '3', '2', ' ', ' ', '1', '8', '.', '0', '0']

In [16]:
housing_data

[[0.00632,
  18.0,
  2.31,
  0.0,
  0.538,
  6.575,
  65.2,
  4.09,
  1.0,
  296.0,
  15.3,
  396.9,
  4.98,
  24.0],
 [0.02731,
  0.0,
  7.07,
  0.0,
  0.469,
  6.421,
  78.9,
  4.9671,
  2.0,
  242.0,
  17.8,
  396.9,
  9.14,
  21.6],
 [0.02729,
  0.0,
  7.07,
  0.0,
  0.469,
  7.185,
  61.1,
  4.9671,
  2.0,
  242.0,
  17.8,
  392.83,
  4.03,
  34.7],
 [0.03237,
  0.0,
  2.18,
  0.0,
  0.458,
  6.998,
  45.8,
  6.0622,
  3.0,
  222.0,
  18.7,
  394.63,
  2.94,
  33.4],
 [0.06905,
  0.0,
  2.18,
  0.0,
  0.458,
  7.147,
  54.2,
  6.0622,
  3.0,
  222.0,
  18.7,
  396.9,
  5.33,
  36.2],
 [0.02985,
  0.0,
  2.18,
  0.0,
  0.458,
  6.43,
  58.7,
  6.0622,
  3.0,
  222.0,
  18.7,
  394.12,
  5.21,
  28.7],
 [0.08829,
  12.5,
  7.87,
  0.0,
  0.524,
  6.012,
  66.6,
  5.5605,
  5.0,
  311.0,
  15.2,
  395.6,
  12.43,
  22.9],
 [0.14455,
  12.5,
  7.87,
  0.0,
  0.524,
  6.172,
  96.1,
  5.9505,
  5.0,
  311.0,
  15.2,
  396.9,
  19.15,
  27.1],
 [0.21124,
  12.5,
  7.87,
  0.0,
  0.524,


y_vals: ค่าที่เราต้องการทำนาย คือ MEDV (ราคาบ้าน)

x_vals: ค่าคุณลักษณะทั้งหมดที่เลือกใช้ (ตาม cols_used)

In [ ]:
y_vals = np.transpose([np.array([y[13] for y in housing_data])])
# np.transpose() ใช้เพื่อเปลี่ยนลิสต์จากแนวนอนเป็นแนวตั้ง (เป็นแถวเดียว) เพื่อให้เหมาะกับการใช้งานกับ TensorFlow หรือโมเดลต่าง ๆ ที่ต้องการข้อมูลเป็น แนวตั้ง (1D array)
# NumPy array ซึ่งเหมือนกับลิสต์ แต่สามารถทำคำนวณแบบเวกเตอร์ได้ง่าย เช่น การบวก ลบ คูณ หารทีละหลายตัวพร้อมกัน

x_vals = np.array([[x for i,x in enumerate(y) if housing_header[i] in cols_used] for y in housing_data]) 
# สำหรับแต่ละบ้าน (y) จะสร้างลิสต์ของค่าของ x (ค่าจากคอลัมน์ต่าง ๆ) ที่ตรงกับคอลัมน์ใน cols_used

In [18]:
housing_data

[[0.00632,
  18.0,
  2.31,
  0.0,
  0.538,
  6.575,
  65.2,
  4.09,
  1.0,
  296.0,
  15.3,
  396.9,
  4.98,
  24.0],
 [0.02731,
  0.0,
  7.07,
  0.0,
  0.469,
  6.421,
  78.9,
  4.9671,
  2.0,
  242.0,
  17.8,
  396.9,
  9.14,
  21.6],
 [0.02729,
  0.0,
  7.07,
  0.0,
  0.469,
  7.185,
  61.1,
  4.9671,
  2.0,
  242.0,
  17.8,
  392.83,
  4.03,
  34.7],
 [0.03237,
  0.0,
  2.18,
  0.0,
  0.458,
  6.998,
  45.8,
  6.0622,
  3.0,
  222.0,
  18.7,
  394.63,
  2.94,
  33.4],
 [0.06905,
  0.0,
  2.18,
  0.0,
  0.458,
  7.147,
  54.2,
  6.0622,
  3.0,
  222.0,
  18.7,
  396.9,
  5.33,
  36.2],
 [0.02985,
  0.0,
  2.18,
  0.0,
  0.458,
  6.43,
  58.7,
  6.0622,
  3.0,
  222.0,
  18.7,
  394.12,
  5.21,
  28.7],
 [0.08829,
  12.5,
  7.87,
  0.0,
  0.524,
  6.012,
  66.6,
  5.5605,
  5.0,
  311.0,
  15.2,
  395.6,
  12.43,
  22.9],
 [0.14455,
  12.5,
  7.87,
  0.0,
  0.524,
  6.172,
  96.1,
  5.9505,
  5.0,
  311.0,
  15.2,
  396.9,
  19.15,
  27.1],
 [0.21124,
  12.5,
  7.87,
  0.0,
  0.524,


In [19]:
y_vals

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [ ]:
# Normalize ข้อมูลให้มีค่าอยู่ระหว่าง 0-1 โดยใช้ min-max scaling
# ปรับข้อมูลให้อยู่ในช่วง 0 ถึง 1 (Normalization) แบบ min-max scaling ซึ่งเป็นขั้นตอนสำคัญมากใน Machine Learning โดยเฉพาะกับอัลกอริธึมที่อ่อนไหวต่อค่าขนาด เช่น KNN หรือ Neural Network
# a.min(0) → หาค่าต่ำสุด "ในแต่ละคอลัมน์":


# [1, 2, 3]   ← แถวที่ 1  
# [4, 5, 6]   ← แถวที่ 2  
# ↓ ↓ ↓
# [1, 2, 3]   ← ค่า min ในแต่ละคอลัมน์

x_vals = (x_vals - x_vals.min(0)) / x_vals.ptp(0)

# เอา ค่ามากสุด (peak) ลบด้วย ค่าต่ำสุด (trough)
# ทำแบบนี้ ในแต่ละคอลัมน์ (เพราะ axis=0)
# ใช้เพื่อหา ช่วงของค่าฟีเจอร์ (range) → สำหรับการ Normalize ให้เป็น 0-1


# x = np.array([
#     [10, 20, 30],
#     [40, 50, 60],
#     [70, 80, 90]
# ])

# การทำงานของ x.ptp(0):
# คอลัมน์ที่ 1: 70 - 10 = 60
# คอลัมน์ที่ 2: 80 - 20 = 60
# คอลัมน์ที่ 3: 90 - 30 = 60

# สูตรการทำ Min-Max Normalization
# จะปรับให้ข้อมูลแต่ละคอลัมน์อยู่ในช่วง [0, 1]
# ทำให้ฟีเจอร์แต่ละตัวมีน้ำหนักเท่า ๆ กัน ไม่ให้ฟีเจอร์ที่ค่ามากกว่าครอบงำฟีเจอร์อื่น


In [ ]:
# แบ่งข้อมูลออกเป็นชุดฝึก (Train set) และ ชุดทดสอบ (Test set) 

# เลือก index แบบสุ่ม จำนวน 80% ของข้อมูลทั้งหมด (len(x_vals)*0.8)
# replace=False หมายถึง ไม่สุ่มซ้ำ
# ได้ผลลัพธ์เป็น index ที่ใช้ฝึกโมเดล

# np.random.choice(array, size, replace=False)
# พารามิเตอร์	  ความหมาย
# array	        แหล่งข้อมูลที่ต้องการสุ่มจาก (สามารถเป็นจำนวนเต็มก็ได้ เช่น 10 คือ [0,1,...,9])
# size	        จำนวนตัวอย่างที่ต้องการสุ่ม
# replace	    ถ้า True → สุ่มซ้ำได้, ถ้า False → สุ่มแบบไม่ซ้ำ

train_indices = np.random.choice(len(x_vals), round(len(x_vals)*0.8), replace=False)


# หาค่าที่ไม่ได้อยู่ใน train_indices
# 1. range(len(x_vals))
# สร้างลิสต์ของ index ทั้งหมด
# เช่น ถ้า x_vals มี 5 แถว → ได้ [0, 1, 2, 3, 4]
# 2. set(...)
# แปลงเป็น set เพื่อให้ลบกันได้ง่าย เช่น {0,1,2,3,4}
# 3. set(...) - set(train_indices)
# เอา index ทั้งหมด ลบกับ index ที่ใช้ฝึก
# เหลือเฉพาะ index ที่ยังไม่ได้ใช้ → คือชุดทดสอบ
# 4. list(...) และ np.array(...)
# แปลงกลับเป็น list → แล้วแปลงเป็น NumPy array → เพื่อใช้กับ x_vals[...]
test_indices = np.array(list(set(range(len(x_vals))) - set(train_indices)))


# นำ index ที่ได้มาเลือกเฉพาะแถวของข้อมูล x_vals และ y_vals
x_vals_train = x_vals[train_indices]
x_vals_test = x_vals[test_indices]
y_vals_train = y_vals[train_indices]
y_vals_test = y_vals[test_indices]


In [22]:
# ตั้งค่า TensorFlow
# กำหนดค่า k = 4 สำหรับ k-NN
# สร้าง placeholder สำหรับข้อมูลฝึก, ข้อมูลทดสอบ, ค่าที่ต้องการทำนาย
k = 4

# ตั้งค่า batch size = ขนาดของชุดทดสอบ (จะทำนายทั้งหมดในคราวเดียว)
batch_size = len(x_vals_test)

# placeholder
# "เตรียมช่องรับข้อมูล 2 คอลัมน์
# และจำนวนแถวเท่าไหร่ก็ได้ (None)
# แล้วฉันจะใส่ข้อมูลลงในช่องนี้ภายหลัง"

# ทำไมต้องใช้ placeholder?
# เพราะใน TensorFlow v1 ต้องสร้าง กราฟการคำนวณล่วงหน้า ก่อน
# เราจะ "ใส่ข้อมูลจริง" ตอน sess.run(...)
x_data_train = tf.placeholder(shape=[None, num_features], dtype=tf.float32)
x_data_test = tf.placeholder(shape=[None, num_features], dtype=tf.float32)
y_target_train = tf.placeholder(shape=[None, 1], dtype=tf.float32)
y_target_test = tf.placeholder(shape=[None, 1], dtype=tf.float32)

In [26]:
# คำนวณระยะห่างและเลือก k ใกล้สุด
# expand_dims เพื่อเพิ่มมิติจะทำให้ x_data_test กลายเป็นเทนเซอร์ 3D ที่มีขนาด (n_samples_test, 1, num_features) 
# การใช้ expand_dims จะเพิ่มมิติที่ตำแหน่งที่ 1 ของ x_data_test ซึ่งทำให้ข้อมูลเปลี่ยนจากเทนเซอร์ 2D (ตัวอย่าง x ฟีเจอร์) ให้กลายเป็นเทนเซอร์ 3D ที่มีขนาด (n_samples_test, 1, num_features)
# พื่อให้สามารถทำการคำนวณระยะห่างระหว่าง x_data_train และ x_data_test ได้


# เราต้องการคำนวณระยะห่าง (distance) ระหว่างตัวอย่าง ทุกตัวใน x_data_train กับทุกตัวใน x_data_test.
# หากข้อมูลของเราเป็น 2D tensor (x_data_train และ x_data_test), การลบระหว่าง 2D tensor โดยตรงจะไม่ได้ผลเนื่องจากจำนวนมิติของมันไม่ตรงกัน (จำนวนตัวอย่างใน x_data_train และ x_data_test อาจแตกต่างกัน).


# x_data_train = [[1, 2, 3], [4, 5, 6]]
# x_data_test = [[2, 2, 2], [3, 3, 3]]
# x_data_test_expanded = [[[2, 2, 2], [2, 2, 2]],
#                         [[3, 3, 3], [3, 3, 3]]]

# manhatt
# tf.subtract(x_data_train, x_data_test_expanded) = [
#    [[1-2, 2-2, 3-2], [1-2, 2-2, 3-2]],
#    [[4-3, 5-3, 6-3], [4-3, 5-3, 6-3]]
# ]
# ได้
# [[[ -1,  0,  1], [-1,  0,  1]],
#  [[  1,  2,  3], [ 1,  2,  3]]]

# tf.abs
# [
#   [[1, 0, 1], [2, 3, 4]],
#   [[2, 1, 0], [1, 2, 3]]
# ]

# reduce_sum หาผลรวมของค่าต่าง ๆ ตามแกน (axis) ที่กำหนดไว้ใน Tensor หรืออาร์เรย์หลายมิติ เป็นผลรวมของระยะห่าง:
# distance = [
#   [2, 2],
#   [6, 6]
# ] 


distance = tf.reduce_sum(tf.abs(tf.subtract(x_data_train, tf.expand_dims(x_data_test,1))), reduction_indices=2)

# คำนวณ Euclidean Distance
# distance_euclidean = tf.sqrt(tf.reduce_sum(tf.square(tf.subtract(x_data_train, tf.expand_dims(x_data_test, 1))), axis=2))


# เลือก k ตัวอย่างในชุดฝึก (train) ที่มีระยะทาง ใกล้ที่สุด กับแต่ละตัวอย่างในชุดทดสอบ (test) โดยใช้ TensorFlow ฟังก์ชัน tf.nn.top_k
# ❷ tf.negative(distance)
# เปลี่ยนค่าระยะห่างทั้งหมดให้เป็นค่าติดลบ
# เพราะ tf.nn.top_k จะเลือก ค่าสูงสุด (เราอยากได้ "ใกล้ที่สุด" → คือ "ค่าต่ำสุด" → จึงต้องใส่ลบ)
top_k_xvals, top_k_indices = tf.nn.top_k(tf.negative(distance), k=k)


In [33]:
top_k_xvals

<tf.Tensor 'TopKV2:0' shape=(?, 4) dtype=float32>

In [ ]:
# ในขั้นตอนถัดไปคุณจะนำค่าระยะห่างเหล่านี้ไปใช้ในการเลือก k เพื่อนบ้านที่ใกล้ที่สุด (top-k nearest neighbors) และคำนวณค่าเฉลี่ยแบบถ่วงน้ำหนักเพื่อทำการทำนายผล.
# 1. คำนวณผลรวมของ top_k_xvals ตามมิติ 1 (ที่เราต้องการหาผลรวมของระยะห่างในแต่ละแถว)
x_sums = tf.expand_dims(tf.reduce_sum(top_k_xvals, 1), 1)  # เพิ่มมิติที่ 1 (ทำให้เป็น 2D tensor)

# 2. ทำการสร้างเทนเซอร์ที่มีค่าทั้งหมดเป็น 1 เพื่อให้สามารถคูณกับ x_sums (repeated sum)

# top_k_xvals = [
#   [-2.0, -2.0],
#   [-6.0, -6.0]
# ]

# x_sums = [
#   [-4.0],
#   [-12.0]
# ]

# x_val_weights = top_k_xvals / x_sums

# TensorFlow จะ error เพราะ shape ไม่ตรง
# เราจึง สร้าง x_sums_repeated ให้มีขนาดเท่ากันกับ top_k_xvals:

# tf.ones([1, 2]) = [[1.0, 1.0]]

    
# x_sums_repeated = [
#   [-4.0, -4.0],
#   [-12.0, -12.0]
# ]


# tf.matmul คือฟังก์ชันของ TensorFlow สำหรับการ คูณเมทริกซ์ (matrix multiplication) โดยเฉพาะครับ
# ไม่ใช่การคูณแบบ element-wise (คูณตามตำแหน่ง) แต่เป็น คูณแบบเมทริกซ์จริง ๆ ตามหลักคณิตศาสตร์เชิงเส้น


x_sums_repeated = tf.matmul(x_sums, tf.ones([1, k], tf.float32))  # ขยาย x_sums ให้มีขนาดเท่ากับ k

# 3. คำนวณค่าน้ำหนัก (weights) ของแต่ละเพื่อนบ้านจากระยะห่าง
# ค่าน้ำหนักจะเป็นการหารค่า top_k_xvals ด้วยผลรวมที่เราคำนวณจากทุก ๆ เพื่อนบ้าน
#  เพิ่มมิติใหม่ที่ตำแหน่งที่ 1 ทำให้ tensor เปลี่ยนจาก [batch_size, k] → [batch_size, 1, k] 
# การ เพิ่มมิติใหม่ที่ตำแหน่งที่ 1 (tf.expand_dims(..., 1)) เป็นการแปลงรูป tensor จาก [batch_size, k] เป็น [batch_size, 1, k] เพื่อให้สามารถนำไปใช้ในการคูณกับค่าจริง (y_target) ในขั้นตอนถัดไปได้
# เพราะในขั้นตอนถัดไป  จะต้องเอา tensor ขนาด [batch_size, 1, k]
# ไปคูณกับ [batch_size, k, 1] เพื่อให้ได้ค่าเฉลี่ยแบบถ่วงน้ำหนักที่เป็น [batch_size, 1, 1] ->สำหรับแต่ละตัวอย่างใน batch (ที่มีขนาดเป็น batch_size), จะได้ผลลัพธ์เป็น หนึ่งค่าทำนาย (single predicted value).

x_val_weights = tf.expand_dims(tf.divide(top_k_xvals, x_sums_repeated), 1)  # ค่าน้ำหนัก


# 4. ดึงค่าของ y_target_train ที่ตรงกับ top_k_indices ซึ่งคือค่าจริงของเพื่อนบ้านที่ใกล้ที่สุด
# top_k_indices คือดัชนี (indices) ของ k เพื่อนบ้านที่ใกล้ที่สุด จากชุดฝึก (training set) สำหรับตัวอย่างในชุดทดสอบ (test set)
# y_target_train คือค่าจริง (true labels) ของตัวอย่างในชุดฝึก
# tf.gather ใช้เพื่อดึงค่าจริงที่ตรงกับดัชนีใน top_k_indices สำหรับแต่ละตัวอย่างในชุดทดสอบ
top_k_yvals = tf.gather(y_target_train, top_k_indices)  # ค่าจริงจากเพื่อนบ้านที่ใกล้ที่สุด

# 5. คำนวณค่าทำนาย (prediction) โดยการคูณน้ำหนักกับค่าจริง
# x_val_weights: ค่าน้ำหนัก (weights) ที่คำนวณจากระยะห่างระหว่างตัวอย่างในชุดฝึกและชุดทดสอบ โดยจะมีขนาดเป็น [batch_size, 1, k]
# top_k_yvals: ค่าจริงของเพื่อนบ้านที่ใกล้ที่สุดที่ได้จากขั้นตอนที่แล้ว โดยมีขนาดเป็น [batch_size, k, 1]
# tf.matmul(x_val_weights, top_k_yvals): การคูณเมทริกซ์ระหว่าง x_val_weights และ top_k_yvals จะให้ผลลัพธ์เป็น [batch_size, 1, 1] ซึ่งเป็นการคำนวณ ค่าเฉลี่ยแบบถ่วงน้ำหนัก สำหรับแต่ละตัวอย่างในชุดทดสอบ
# tf.squeeze(..., axis=1): หลังจากที่ได้ผลลัพธ์เป็น [batch_size, 1, 1], การใช้ tf.squeeze() เพื่อลบมิติที่ไม่จำเป็น (มิติที่มีขนาดเป็น 1) ออก จะทำให้ผลลัพธ์สุดท้ายเป็น [batch_size] ซึ่งเป็น ค่าทำนายสุดท้าย (predictions) สำหรับแต่ละตัวอย่าง
prediction = tf.squeeze(tf.matmul(x_val_weights, top_k_yvals), axis=1)  # คำนวณค่าทำนายสุดท้าย



In [ ]:
# คำนวณ Mean Squared Error (MSE)

# tf.reduce_sum(...):
# คำสั่งนี้ใช้ในการ หาผลรวม ของค่าผลต่างยกกำลังสอง (error squared) ที่ได้จากขั้นตอนที่แล้ว:
    
# tf.divide(..., batch_size):
# ขั้นตอนนี้ใช้ในการ หารผลรวมของ squared errors ด้วยจำนวน batch_size เพื่อคำนวณ ค่าเฉลี่ย (mean) ของค่า squared errors สำหรับแต่ละตัวอย่างในชุดทดสอ

mse = tf.divide(tf.reduce_sum(tf.square(tf.subtract(prediction, y_target_test))), batch_size)


In [32]:
mse

<tf.Tensor 'truediv_3:0' shape=() dtype=float32>

In [35]:
batch_size

101

In [ ]:
num_loops = int(np.ceil(len(x_vals_test)/batch_size)) # โค้ดนี้ใช้ในการ คำนวณจำนวน batch ที่จะต้องใช้ในการทดสอบทั้งหมด โดยการหารจำนวนตัวอย่างในชุดทดสอบ x_vals_test ด้วย batch_size 
# และใช้ np.ceil เพื่อทำให้จำนวน batch เป็นจำนวนเต็ม (rounded up) เมื่อมีข้อมูลไม่ครบใน batch สุดท้าย.
for i in range(num_loops): # ใช้ในการวนลูปเพื่อประมวลผลแต่ละ batch ของข้อมูลทดสอบ (test set).
    min_index = i * batch_size
    
#     max_index = min((i+1) * batch_size, len(x_vals_train)):
# (i+1) * batch_size คือดัชนีสุดท้ายของ batch ที่ i.
# เช่น ถ้า i = 0 และ batch_size = 10 max_index จะเป็น 1 * 10 = 10 (แสดงว่าข้อมูลใน batch ที่ 0 จะไปถึงข้อมูลตัวที่ 9).
# แต่เนื่องจากข้อมูลทั้งหมดอาจไม่หารด้วย batch_size ลงตัว ทำให้ max_index จะไม่เกิน จำนวนข้อมูลทั้งหมด (ซึ่งคือ len(x_vals_train)).
# ใช้ min() เพื่อให้ max_index ไม่เกินจำนวนข้อมูลทั้งหมด. หาก (i+1) * batch_size มากกว่าจำนวนข้อมูลในชุดฝึก (train set) ระบบจะเลือกให้ max_index เท่ากับ len(x_vals_train).
# ตัวอย่าง:

# ถ้า i = 0 และ batch_size = 10 และ len(x_vals_train) = 50, max_index = min(1 * 10, 50) = 10
# ถ้า i = 4 และ batch_size = 10 และ len(x_vals_train) = 50, max_index = min(5 * 10, 50) = 50
# ถ้า i = 5 และ batch_size = 10 และ len(x_vals_train) = 50, max_index = min(6 * 10, 50) = 50 (คือไม่ให้ max_index เกินจำนวนข้อมูลในชุดฝึก)

    max_index = min((i+1) * batch_size, len(x_vals_train))
    x_batch = x_vals_test[min_index:max_index]
    y_batch = y_vals_test[min_index:max_index]

    predictions = sess.run(prediction, feed_dict={
        x_data_train: x_vals_train,
        x_data_test: x_batch,
        y_target_train: y_vals_train,
        y_target_test: y_batch
    })

    batch_mse = sess.run(mse, feed_dict={
        x_data_train: x_vals_train,
        x_data_test: x_batch,
        y_target_train: y_vals_train,
        y_target_test: y_batch
    })

    print('Batch #' + str(i+1) + ' MSE: ' + str(np.round(batch_mse, 3)))


Batch #1 MSE: 22.946
